//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount
    {
        public string customerUserName { get; set; }
        public string customerPassword { get; set; }
        public string customerPassword2 { get; set; }
        public string customerEmail { get; set; }
        public string customerPhoneNumber { get; set; }
    }
}
